### ISSUE TITLE
WebsocketClient fails

### ISSUE THREAD

**Issue by johnjelinek** [coinbase/gdax-node#4] opened 2016-07-24 22:02 UTC
code:

```
new Gdax.WebsocketClient();
```

output:

```
{ type: 'done',
  order_type: 'limit',
  side: 'sell',
  sequence: 1286880417,
  order_id: '59719169-ac79-4e55-99c7-64ea487d6ed7',
  reason: 'canceled',
  product_id: 'BTC-USD',
  time: '2016-07-24T21:59:50.613571Z',
  price: '662.48',
  remaining_size: '0.29' }
undefined:1
{"type":"done","order_type":"limit","side":"sell","sequence":1286880418,"order_id":"5160f16e-264b-4e24-8adf-ca988b6c4d26","reason":"canceled","product_id":"BTC-USD","time":"2016-07-24T21:59:50.63179Z","price":"662.39","remaining_size":"0.43"



SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at prototype.onMessage (/mnt/c/Users/John Jelinek/Documents/gdax/node_modules/gdax/lib/clients/websocket.js:68:31)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/WebSocket.js:798:10)
    at /mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/Receiver.js:473:18
    at /mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/Receiver.js:357:7
    at /mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)
```

I can't seem to swallow this error.

**Comment by ahalekelly** [comment] 2016-10-10 05:32
I had the same problem after updating from Node 6.2.2 to 6.3.0, which seemed to be resolved by updating ws to the latest version, 1.1.1

**Comment by chrisinajar** [comment] 2016-10-11 22:30
Duplicate of https://github.com/coinbase/gdax-node/issues/3

**Comment by loriopatrick** [comment] 2016-12-15 18:48
https://github.com/coinbase/gdax-node/issues/9

**Closed by loriopatrick** 2016-12-15 18:48 UTC
