### ISSUE TITLE
WS - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by dbrans** [coinbase/gdax-node#9] opened 2016-08-23 00:28 UTC
First reported here:
https://community.coinbase.com/t/unexpected-end-of-json-input-error-with-gdax-library-for-node-js/12382

``` stacktrace
undefined:1
{"type":"done","order_type":"limit","side":"sell","sequence":1411617737,"order_id":"7741a72e-0635-4fd9-a8ca-d9d3afd65fa6","reason":"canceled","product_id":"BTC-USD","time":"2016-08-23T00:24:17.125397Z","price":"585.26","remaining_size":"0.97"


SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at prototype.onMessage (myproject/node_modules/gdax/lib/clients/websocket.js:68:31)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (myproject/node_modules/ws/lib/WebSocket.js:798:10)
```

**Comment by dbrans** [comment] 2016-08-23 05:01
This seems to be an issue with node 6.4. It does not seem to happen with node 4.4.

**Comment by ahalekelly** [comment] 2016-10-10 05:29
I had the same problem after updating from Node 6.2.2 to 6.3.0, which seemed to be resolved by updating ws to the latest version, 1.1.1

**Comment by chrisinajar** [comment] 2016-10-11 22:30
Duplicate of https://github.com/coinbase/gdax-node/issues/3

**Comment by loriopatrick** [comment] 2016-12-15 18:47
We had a temporary issue with our server side feed. This has been resolved.

**Closed by loriopatrick** 2016-12-15 18:47 UTC
