### ISSUE TITLE
using Promises

### ISSUE THREAD

**Issue by tcnevin** [coinbase/gdax-node#211] opened 2018-01-09 00:16 UTC
https://github.com/coinbase/gdax-node/blob/master/README.md#using-promises

The documentation here says promises can be used unless otherwise specified.
When looking through most of the files in /lib or /lib/clients
I only see a new promise written for .deleteNext

also, promises aren't working for me and unless I specify a callback on getAccounts() for example,
I get an error saying a callback is required.

 I saw closed issues relating to this.
  https://github.com/coinbase/gdax-node/issues/111
  https://github.com/coinbase/gdax-node/issues/144

the answer seems to be 
npm install coinbase/gdax-node    or
yarn add coinbase/gdax-node

but when I try that, the binary can't be found.

**Comment by rmm5t** [comment] 2018-01-09 01:32
Dupe of #148 

> the answer seems to be
> ```
> npm install coinbase/gdax-node 
> # or
> yarn add coinbase/gdax-node
> ```

Correct. That is the current workaround.

> but when I try that, the binary can't be found.

🤔 Bizarre. Could you be more specific? What's the exact error? What version of `npm` are you running?

**Comment by tcnevin** [comment] 2018-01-09 01:47
npm -v 5.6.0
node -v 9.2.1

//This Code ...
const callbackProfile = (err,response,data)=>{console.log(data[0].profile_id); console.log(profile);}

authedClient.getAccounts().then(data => {console.log(data);
                // work with data
            })
            .catch(error => {
                // handle the error
            });
//Produces this error

authedClient.getAccounts(callbackProfile).then(data => {console.log(data);
                                         ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (/var/AlgoTrader/gdaxView.js:11:42)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

//If I remove the callback, I get this

 throw "Must supply a callback"
      ^
Must supply a callback

**Comment by rmm5t** [comment] 2018-01-09 02:16
You must have `git` installed for `npm install` to work against a github repository.

(please close this issue)

**Comment by tcnevin** [comment] 2018-01-09 02:17
Does npm install coinbase/gdax-node use the code from this repository?
I don't see Promises very often defined in the /lib
Could you please show me a link to the source which defines the new Promises

**Comment by rmm5t** [comment] 2018-01-09 02:21
> Does npm install coinbase/gdax-node use the code from this repository?

Yes. 

> I don't see Promises very often defined in the /lib

I don't understand what you mean here. Every single API method has support for them. If no `callback` is supplied, all client methods return a promise.

> Could you please show me a link to the source which defines the new Promises

https://github.com/coinbase/gdax-node/blob/master/lib/clients/public.js#L79-L101

**Comment by tcnevin** [comment] 2018-01-09 02:37
Thank you. That makes sense, checking !callback on line 80
I missed that originally, and AuthedClient extends PublicClient 

Sorry for the trouble, maybe add the yarn/npm instructions to the installation instructions

e.g
# from GitHub
npm install coinbase/gdax-node (required for using promises)

**Comment by rmm5t** [comment] 2018-01-09 02:41
@tcnevin, No worries. It's all covered in #148.

Please close this issue.

**Closed** 2018-01-09 03:06 UTC
