### ISSUE TITLE
Deposit Address / Tx Hash through API?

### ISSUE THREAD

**Issue by LRonHubs** [coinbase/gdax-node#127] opened 2017-10-23 21:26 UTC
Is it possible to get the txHash of a deposit, or txHash of a withdrawal, through the API? This information is available on my GDAX account page but not through the API? That is sour

**Comment by fb55** [comment] 2017-10-25 06:22
Duplicate of #91

**Closed by fb55** 2017-10-25 06:22 UTC

**Comment by LRonHubs** [comment] 2017-10-25 22:33
Transasction hash is different from deposit address

**Comment by fb55** [comment] 2017-10-25 22:54
Withdrawal calls aren't synchronous, that's why we don't provide a transaction hash.

**Comment by LRonHubs** [comment] 2017-10-25 23:19
In the Deposit and Withdrawal History call.... u guys are severely lacking in ur info there, but in the history page of the website it is available

**Comment by danielebuso** [comment] 2017-11-16 19:19
+1

**Comment by LRonHubs** [comment] 2017-11-16 20:44
Yea it's pretty fucked up that this still isnt implemented

**Comment by LRonHubs** [comment] 2017-11-16 20:44
And that the issue is still closed

**Comment by LRonHubs** [comment] 2017-11-16 20:45
https://github.com/coinbase/gdax-node/issues/142

**Comment by jannotti** [comment] 2018-01-03 03:09
@fb55 It's understandable that the txHash is not returned immediately when withdrawCrypto() is called because, as you say, the call needs to return synchronously and the hash doesn't exist yet.  But it's a problem that the hash is also not available when one later calls getAccountHistory().  That returns an array of things that have changed the account's balance, including withdrawals.  And each withdrawal has a 'details' field which contains only
```
 details:
     { transfer_id: 'f46bc478-eed4-42f0-be97-742d8052d13b',
       transfer_type: 'withdraw' } },
```
This seems similar to the data that's available on the gdax Accounts:History tab.  But, lo and behold, under the Accounts:Transfers tab of the gdax UI, one can see the blockchain transaction hash associated with the withdrawal.  So I suspect the info is readily available, but from an undocumented API call.  Could you document that call and add it to the node bindings?

**Comment by jannotti** [comment] 2018-01-04 03:25
Well, until they add it to Gdax.AuthenticatedClient, you can do it yourself with:
```
function getAccountTransfers(accountID, args = {}, callback) {
  if (!callback && typeof args === 'function') {
    callback = args;
    args = {};
  }
  return this.get(['accounts', accountID, 'transfers'], { qs: args }, callback);
}
Gdax.AuthenticatedClient.prototype.getAccountTransfers = getAccountTransfers;
```
