### ISSUE TITLE
WebsocketClient RangeError

### ISSUE THREAD

**Issue by woudsma** [coinbase/gdax-node#10] opened 2016-09-24 11:28 UTC
Using Node v6.6.0 on Mac OSX - 2.3GHz i7 w. 16gb RAM
Usually happens within the first 10 seconds.

```
/path/to/project/node_modules/ws/lib/Receiver.js:382
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
at RangeError (native)
at fastCopy (/path/to/project/node_modules/ws/lib/Receiver.js:382:24)
at Receiver.add (/path/to/project/node_modules/ws/lib/Receiver.js:82:3)
at TLSSocket.firstHandler (/path/to/project/node_modules/ws/lib/WebSocket.js:775:22)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
at TLSSocket.Readable.push (_stream_readable.js:134:10)
at TLSWrap.onread (net.js:543:20)
```

Also getting:

```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at WebsocketClient.prototype.onMessage (/path/to/project/node_modules/gdax/lib/clients/websocket.js:68:31)
```

**Comment by ahalekelly** [comment] 2016-10-10 05:31
I had the same problem after updating from Node 6.2.2 to 6.3.0, which seemed to be resolved by updating ws to the latest version, 1.1.1

**Comment by chrisinajar** [comment] 2016-10-11 22:30
Duplicate of https://github.com/coinbase/gdax-node/issues/3

**Comment by loriopatrick** [comment] 2016-12-15 18:51
Resolved

**Closed by loriopatrick** 2016-12-15 18:51 UTC
