### ISSUE TITLE
getProductTrades in AuthClient

### ISSUE THREAD

**Issue by onedayitwillmake** [coinbase/gdax-node#165] opened 2017-12-18 04:11 UTC
It looks like `getProductTrades` looks at `this.productID`, which if using an `Authenticated` client is not yet

```javascript
getProductTrades(args = {}, callback) {
    if (!callback && typeof args === 'function') {
      callback = args;
      args = {};
    }
    return this.get(
      ['products', this.productID, 'trades'],
      { qs: args },
      callback
    );
  }
```

As a work around, i'm simply explicitly setting it on the authClient before the call

**Comment by tkriplean** [comment] 2017-12-21 21:29
Duplicate of https://github.com/coinbase/gdax-node/issues/117

Note that it isn't clear to me whether there is a team supporting this "official" GDAX client.

**Comment by fb55** [comment] 2017-12-24 22:22
@trkiplean Thanks for flagging!

We do support it, it (hopefully understandably) isn’t at the top of the priority list tho :)

**Closed by fb55** 2017-12-24 22:22 UTC

**Comment by tkriplean** [comment] 2017-12-27 22:13
@fb55: thanks! I'm glad to see the support and know whom several of the official supporters are :) I understand the prioritization. Keep up the good work!

**Comment by rmm5t** [comment] 2017-12-27 23:27
@tkriplean Just to clarify, `getProductTrades()` now accepts a `productID` as the first argument as part of PR #178. Just re-sync with the `master` branch. 

```
npm install coinbase/gdax-node
```
