### ISSUE TITLE
pageArgs Not Consistent With Header Response

### ISSUE THREAD

**Issue by patwhite** [coinbase/gdax-node#381] opened 2019-09-05 16:49 UTC
Hi, I'm trying to paginate through results and can't seem to figure out an issue. The header response for a call to getAccountTransfers returns cb-after as a ISO time stamp, see here: "2019-09-03 18:04:35.655243+00".

However, the api library only accepts a number for the before / after parameters.  Should I be converting that to epoch time? Any advice on how to page items?

**Comment by vansergen** [comment] 2019-09-07 15:30
It corresponds to the `created_at` property of the first/last element https://github.com/coinbase/coinbase-pro-node/issues/326

You can test it like this (which is equivalent to the request with no `after` parameter):
```javascript
authClient.getAccountTransfers(
  'account-id',
  { after: new Date().toISOString() },
  cb
);
```

**Comment by Nicholas-t** [comment] 2019-09-09 17:07
I am getting this error  'Invalid positive integer value for parameter - after' any other suggestions?
thanks in advance

**Comment by vansergen** [comment] 2019-09-10 11:51
@Nicholas-t I couldn't reproduce this error. Can you provide code you used? This works fine for me:
```javascript
let limit = 10;
let accound_id = 'your-account-id';
authClient.getAccountTransfers(accound_id, { limit }, (error, response, data) => {
  if (error) {
    console.error(error);
  } else {
    let after = response.headers['cb-after'];
    let before = response.headers['cb-before'];
    console.log(before === data[0].created_at);
    console.log(after === data[data.length - 1].created_at);
    authClient.getAccountTransfers(
      accound_id,
      { limit, after },
      (error, response, data) => {
        if (error) {
          console.error(error);
        } else {
          console.log(response.headers['cb-before'] === data[0].created_at);
          console.log(
            response.headers['cb-after'] === data[data.length - 1].created_at
          );
        }
      }
    );
  }
});
```

**Comment by drewrothstein** [comment] 2020-01-16 05:43
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed as completed by drewrothstein** 2020-01-16 05:43 UTC
